ALTER TABLE admins ADD COLUMN IF NOT EXISTS parent_admin_id UUID REFERENCES admins(id) ON DELETE SET NULL;
ALTER TABLE admins ADD COLUMN IF NOT EXISTS created_by_superadmin_id UUID REFERENCES admins(id) ON DELETE SET NULL;
ALTER TABLE members ADD COLUMN IF NOT EXISTS created_by_admin_id UUID REFERENCES admins(id) ON DELETE SET NULL;
