// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id, name, phone, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, phone, email, password_hash, created_at, updated_at
`

type CreateAdminParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Phone        sql.NullString `json:"phone"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, name, phone, email, password_hash, created_at, updated_at FROM admins WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, name, phone, email, password_hash, created_at, updated_at FROM admins WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByPhone = `-- name: GetAdminByPhone :one
SELECT id, name, phone, email, password_hash, created_at, updated_at FROM admins WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetAdminByPhone(ctx context.Context, phone sql.NullString) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByPhone, phone)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins
SET password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
`

type UpdateAdminPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminPassword, arg.PasswordHash, arg.ID)
	return err
}
