// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_features.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const aICostByGym = `-- name: AICostByGym :many
SELECT
    a.id AS admin_id,
    a.name AS admin_name,
    COUNT(l.id)::int8 AS total_executions,
    COALESCE(SUM(l.total_tokens), 0)::int8 AS total_tokens,
    COALESCE(SUM(l.estimated_cost), 0.000000)::numeric(10, 6) AS total_cost
FROM admins a
LEFT JOIN superadmin_ai_audit_logs l ON l.admin_id = a.id
WHERE ($1::timestamptz IS NULL OR l.created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR l.created_at <= $2::timestamptz)
GROUP BY a.id, a.name
ORDER BY total_cost DESC
`

type AICostByGymParams struct {
	FromTime sql.NullTime `json:"from_time"`
	ToTime   sql.NullTime `json:"to_time"`
}

type AICostByGymRow struct {
	AdminID         uuid.UUID `json:"admin_id"`
	AdminName       string    `json:"admin_name"`
	TotalExecutions int64     `json:"total_executions"`
	TotalTokens     int64     `json:"total_tokens"`
	TotalCost       float64   `json:"total_cost"`
}

func (q *Queries) AICostByGym(ctx context.Context, arg AICostByGymParams) ([]AICostByGymRow, error) {
	rows, err := q.db.QueryContext(ctx, aICostByGym, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AICostByGymRow
	for rows.Next() {
		var i AICostByGymRow
		if err := rows.Scan(
			&i.AdminID,
			&i.AdminName,
			&i.TotalExecutions,
			&i.TotalTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aIHeavyUsers = `-- name: AIHeavyUsers :many
SELECT
    m.id AS member_id,
    m.name AS member_name,
    a.id AS admin_id,
    a.name AS admin_name,
    COUNT(l.id)::int8 AS total_calls,
    COALESCE(SUM(l.total_tokens), 0)::int8 AS total_tokens,
    COALESCE(SUM(l.estimated_cost), 0.000000)::numeric(10, 6) AS total_cost
FROM members m
JOIN admins a ON m.created_by_admin_id = a.id
JOIN superadmin_ai_audit_logs l ON l.member_id = m.id
WHERE ($1::timestamptz IS NULL OR l.created_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR l.created_at <= $2::timestamptz)
GROUP BY m.id, m.name, a.id, a.name
HAVING COALESCE(SUM(l.total_tokens), 0)::int8 >= $3::int8
ORDER BY total_tokens DESC
LIMIT $4::int
`

type AIHeavyUsersParams struct {
	FromTime   sql.NullTime `json:"from_time"`
	ToTime     sql.NullTime `json:"to_time"`
	Threshold  int64        `json:"threshold"`
	LimitCount int32        `json:"limit_count"`
}

type AIHeavyUsersRow struct {
	MemberID    uuid.UUID `json:"member_id"`
	MemberName  string    `json:"member_name"`
	AdminID     uuid.UUID `json:"admin_id"`
	AdminName   string    `json:"admin_name"`
	TotalCalls  int64     `json:"total_calls"`
	TotalTokens int64     `json:"total_tokens"`
	TotalCost   float64   `json:"total_cost"`
}

func (q *Queries) AIHeavyUsers(ctx context.Context, arg AIHeavyUsersParams) ([]AIHeavyUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, aIHeavyUsers,
		arg.FromTime,
		arg.ToTime,
		arg.Threshold,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AIHeavyUsersRow
	for rows.Next() {
		var i AIHeavyUsersRow
		if err := rows.Scan(
			&i.MemberID,
			&i.MemberName,
			&i.AdminID,
			&i.AdminName,
			&i.TotalCalls,
			&i.TotalTokens,
			&i.TotalCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAIAuditLogs = `-- name: CountAIAuditLogs :one
SELECT COUNT(*) FROM superadmin_ai_audit_logs
WHERE ($1::uuid IS NULL OR admin_id = $1::uuid)
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::text IS NULL OR prompt_type = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
`

type CountAIAuditLogsParams struct {
	AdminID    uuid.NullUUID  `json:"admin_id"`
	MemberID   uuid.NullUUID  `json:"member_id"`
	PromptType sql.NullString `json:"prompt_type"`
	FromTime   sql.NullTime   `json:"from_time"`
	ToTime     sql.NullTime   `json:"to_time"`
}

func (q *Queries) CountAIAuditLogs(ctx context.Context, arg CountAIAuditLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAIAuditLogs,
		arg.AdminID,
		arg.MemberID,
		arg.PromptType,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDailyFoodUploads = `-- name: CountDailyFoodUploads :one
SELECT COUNT(*) FROM member_food_logs WHERE member_id = $1 AND log_date = $2
`

type CountDailyFoodUploadsParams struct {
	MemberID uuid.UUID `json:"member_id"`
	LogDate  time.Time `json:"log_date"`
}

func (q *Queries) CountDailyFoodUploads(ctx context.Context, arg CountDailyFoodUploadsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDailyFoodUploads, arg.MemberID, arg.LogDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDietChartsGenerated = `-- name: CountDietChartsGenerated :one
SELECT COUNT(*) FROM superadmin_ai_audit_logs
WHERE member_id = $1 AND prompt_type = 'diet_chart'
`

func (q *Queries) CountDietChartsGenerated(ctx context.Context, memberID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDietChartsGenerated, memberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemberFoodLog = `-- name: CreateMemberFoodLog :one
INSERT INTO member_food_logs (
    member_id, image_url, device_model, capture_time, ai_response_json, log_date
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, member_id, image_url, device_model, capture_time, ai_response_json, log_date, created_at
`

type CreateMemberFoodLogParams struct {
	MemberID       uuid.UUID             `json:"member_id"`
	ImageUrl       string                `json:"image_url"`
	DeviceModel    sql.NullString        `json:"device_model"`
	CaptureTime    sql.NullTime          `json:"capture_time"`
	AiResponseJson pqtype.NullRawMessage `json:"ai_response_json"`
	LogDate        time.Time             `json:"log_date"`
}

func (q *Queries) CreateMemberFoodLog(ctx context.Context, arg CreateMemberFoodLogParams) (MemberFoodLog, error) {
	row := q.db.QueryRowContext(ctx, createMemberFoodLog,
		arg.MemberID,
		arg.ImageUrl,
		arg.DeviceModel,
		arg.CaptureTime,
		arg.AiResponseJson,
		arg.LogDate,
	)
	var i MemberFoodLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.ImageUrl,
		&i.DeviceModel,
		&i.CaptureTime,
		&i.AiResponseJson,
		&i.LogDate,
		&i.CreatedAt,
	)
	return i, err
}

const getAIPrompt = `-- name: GetAIPrompt :one
SELECT id, prompt_type, prompt_text, is_active, created_at, updated_at, admin_id FROM ai_prompts 
WHERE prompt_type = $1 AND is_active = TRUE AND (admin_id = $2 OR admin_id IS NULL)
ORDER BY admin_id DESC NULLS LAST
LIMIT 1
`

type GetAIPromptParams struct {
	PromptType string        `json:"prompt_type"`
	AdminID    uuid.NullUUID `json:"admin_id"`
}

func (q *Queries) GetAIPrompt(ctx context.Context, arg GetAIPromptParams) (AiPrompt, error) {
	row := q.db.QueryRowContext(ctx, getAIPrompt, arg.PromptType, arg.AdminID)
	var i AiPrompt
	err := row.Scan(
		&i.ID,
		&i.PromptType,
		&i.PromptText,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
	)
	return i, err
}

const getAITokenUsageForUser = `-- name: GetAITokenUsageForUser :one
SELECT
    m.id AS member_id,
    m.name AS member_name,
    COALESCE(SUM(l.prompt_tokens), 0)::int8 AS total_prompt_tokens,
    COALESCE(SUM(l.completion_tokens), 0)::int8 AS total_completion_tokens,
    COALESCE(SUM(l.total_tokens), 0)::int8 AS total_tokens,
    COALESCE(SUM(l.estimated_cost), 0.000000)::numeric(10, 6) AS total_estimated_cost
FROM members m
LEFT JOIN superadmin_ai_audit_logs l ON l.member_id = m.id
WHERE m.id = $1
GROUP BY m.id, m.name
`

type GetAITokenUsageForUserRow struct {
	MemberID              uuid.UUID `json:"member_id"`
	MemberName            string    `json:"member_name"`
	TotalPromptTokens     int64     `json:"total_prompt_tokens"`
	TotalCompletionTokens int64     `json:"total_completion_tokens"`
	TotalTokens           int64     `json:"total_tokens"`
	TotalEstimatedCost    float64   `json:"total_estimated_cost"`
}

// Returns AI token usage and cost for a single member
func (q *Queries) GetAITokenUsageForUser(ctx context.Context, id uuid.UUID) (GetAITokenUsageForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAITokenUsageForUser, id)
	var i GetAITokenUsageForUserRow
	err := row.Scan(
		&i.MemberID,
		&i.MemberName,
		&i.TotalPromptTokens,
		&i.TotalCompletionTokens,
		&i.TotalTokens,
		&i.TotalEstimatedCost,
	)
	return i, err
}

const getAITokenUsagePerAdmin = `-- name: GetAITokenUsagePerAdmin :many
SELECT
    a.id AS admin_id,
    a.name AS admin_name,
    a.email AS admin_email,
    COALESCE(SUM(l.prompt_tokens), 0)::int8 AS total_prompt_tokens,
    COALESCE(SUM(l.completion_tokens), 0)::int8 AS total_completion_tokens,
    COALESCE(SUM(l.total_tokens), 0)::int8 AS total_tokens,
    COALESCE(SUM(l.estimated_cost), 0.000000)::numeric(10, 6) AS total_estimated_cost
FROM admins a
LEFT JOIN superadmin_ai_audit_logs l ON l.admin_id = a.id
GROUP BY a.id, a.name, a.email
ORDER BY total_estimated_cost DESC
`

type GetAITokenUsagePerAdminRow struct {
	AdminID               uuid.UUID `json:"admin_id"`
	AdminName             string    `json:"admin_name"`
	AdminEmail            string    `json:"admin_email"`
	TotalPromptTokens     int64     `json:"total_prompt_tokens"`
	TotalCompletionTokens int64     `json:"total_completion_tokens"`
	TotalTokens           int64     `json:"total_tokens"`
	TotalEstimatedCost    float64   `json:"total_estimated_cost"`
}

// Returns AI token usage and cost per Gym Admin
func (q *Queries) GetAITokenUsagePerAdmin(ctx context.Context) ([]GetAITokenUsagePerAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, getAITokenUsagePerAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAITokenUsagePerAdminRow
	for rows.Next() {
		var i GetAITokenUsagePerAdminRow
		if err := rows.Scan(
			&i.AdminID,
			&i.AdminName,
			&i.AdminEmail,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
			&i.TotalEstimatedCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAITokenUsagePerUser = `-- name: GetAITokenUsagePerUser :many
SELECT
    m.id AS member_id,
    m.name AS member_name,
    m.phone AS member_phone,
    m.created_by_admin_id,
    COALESCE(SUM(l.prompt_tokens), 0)::int8 AS total_prompt_tokens,
    COALESCE(SUM(l.completion_tokens), 0)::int8 AS total_completion_tokens,
    COALESCE(SUM(l.total_tokens), 0)::int8 AS total_tokens,
    COALESCE(SUM(l.estimated_cost), 0.000000)::numeric(10, 6) AS total_estimated_cost
FROM members m
LEFT JOIN superadmin_ai_audit_logs l ON l.member_id = m.id
GROUP BY m.id, m.name, m.phone, m.created_by_admin_id
ORDER BY total_estimated_cost DESC
`

type GetAITokenUsagePerUserRow struct {
	MemberID              uuid.UUID     `json:"member_id"`
	MemberName            string        `json:"member_name"`
	MemberPhone           string        `json:"member_phone"`
	CreatedByAdminID      uuid.NullUUID `json:"created_by_admin_id"`
	TotalPromptTokens     int64         `json:"total_prompt_tokens"`
	TotalCompletionTokens int64         `json:"total_completion_tokens"`
	TotalTokens           int64         `json:"total_tokens"`
	TotalEstimatedCost    float64       `json:"total_estimated_cost"`
}

// Returns AI token usage and cost per member
func (q *Queries) GetAITokenUsagePerUser(ctx context.Context) ([]GetAITokenUsagePerUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAITokenUsagePerUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAITokenUsagePerUserRow
	for rows.Next() {
		var i GetAITokenUsagePerUserRow
		if err := rows.Scan(
			&i.MemberID,
			&i.MemberName,
			&i.MemberPhone,
			&i.CreatedByAdminID,
			&i.TotalPromptTokens,
			&i.TotalCompletionTokens,
			&i.TotalTokens,
			&i.TotalEstimatedCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT setting_key, setting_value, updated_at, admin_id FROM system_settings 
WHERE setting_key = $1 AND (admin_id = $2 OR admin_id IS NULL)
ORDER BY admin_id DESC NULLS LAST
LIMIT 1
`

type GetSystemSettingParams struct {
	SettingKey string        `json:"setting_key"`
	AdminID    uuid.NullUUID `json:"admin_id"`
}

func (q *Queries) GetSystemSetting(ctx context.Context, arg GetSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, arg.SettingKey, arg.AdminID)
	var i SystemSetting
	err := row.Scan(
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.AdminID,
	)
	return i, err
}

const listAIAuditLogs = `-- name: ListAIAuditLogs :many
SELECT id, member_id, admin_id, prompt_type, prompt_text, ai_response_json, prompt_tokens, completion_tokens, total_tokens, estimated_cost, created_at FROM superadmin_ai_audit_logs
WHERE ($1::uuid IS NULL OR admin_id = $1::uuid)
  AND ($2::uuid IS NULL OR member_id = $2::uuid)
  AND ($3::text IS NULL OR prompt_type = $3::text)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
ORDER BY created_at DESC
LIMIT $7::int
OFFSET $6::int
`

type ListAIAuditLogsParams struct {
	AdminID     uuid.NullUUID  `json:"admin_id"`
	MemberID    uuid.NullUUID  `json:"member_id"`
	PromptType  sql.NullString `json:"prompt_type"`
	FromTime    sql.NullTime   `json:"from_time"`
	ToTime      sql.NullTime   `json:"to_time"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

func (q *Queries) ListAIAuditLogs(ctx context.Context, arg ListAIAuditLogsParams) ([]SuperadminAiAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAIAuditLogs,
		arg.AdminID,
		arg.MemberID,
		arg.PromptType,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuperadminAiAuditLog
	for rows.Next() {
		var i SuperadminAiAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.AdminID,
			&i.PromptType,
			&i.PromptText,
			&i.AiResponseJson,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.EstimatedCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIPrompts = `-- name: ListAIPrompts :many
SELECT id, prompt_type, prompt_text, is_active, created_at, updated_at, admin_id FROM ai_prompts ORDER BY prompt_type ASC
`

func (q *Queries) ListAIPrompts(ctx context.Context) ([]AiPrompt, error) {
	rows, err := q.db.QueryContext(ctx, listAIPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiPrompt
	for rows.Next() {
		var i AiPrompt
		if err := rows.Scan(
			&i.ID,
			&i.PromptType,
			&i.PromptText,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberFoodLogs = `-- name: ListMemberFoodLogs :many
SELECT id, member_id, image_url, device_model, capture_time, ai_response_json, log_date, created_at FROM member_food_logs WHERE member_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListMemberFoodLogsParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListMemberFoodLogs(ctx context.Context, arg ListMemberFoodLogsParams) ([]MemberFoodLog, error) {
	rows, err := q.db.QueryContext(ctx, listMemberFoodLogs, arg.MemberID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberFoodLog
	for rows.Next() {
		var i MemberFoodLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.ImageUrl,
			&i.DeviceModel,
			&i.CaptureTime,
			&i.AiResponseJson,
			&i.LogDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAIAuditUsage = `-- name: LogAIAuditUsage :one
INSERT INTO superadmin_ai_audit_logs (
    member_id, admin_id, prompt_type, prompt_text, ai_response_json, 
    prompt_tokens, completion_tokens, total_tokens, estimated_cost
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, member_id, admin_id, prompt_type, prompt_text, ai_response_json, prompt_tokens, completion_tokens, total_tokens, estimated_cost, created_at
`

type LogAIAuditUsageParams struct {
	MemberID         uuid.UUID       `json:"member_id"`
	AdminID          uuid.UUID       `json:"admin_id"`
	PromptType       string          `json:"prompt_type"`
	PromptText       string          `json:"prompt_text"`
	AiResponseJson   json.RawMessage `json:"ai_response_json"`
	PromptTokens     int32           `json:"prompt_tokens"`
	CompletionTokens int32           `json:"completion_tokens"`
	TotalTokens      int32           `json:"total_tokens"`
	EstimatedCost    float64         `json:"estimated_cost"`
}

func (q *Queries) LogAIAuditUsage(ctx context.Context, arg LogAIAuditUsageParams) (SuperadminAiAuditLog, error) {
	row := q.db.QueryRowContext(ctx, logAIAuditUsage,
		arg.MemberID,
		arg.AdminID,
		arg.PromptType,
		arg.PromptText,
		arg.AiResponseJson,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.EstimatedCost,
	)
	var i SuperadminAiAuditLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.AdminID,
		&i.PromptType,
		&i.PromptText,
		&i.AiResponseJson,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.EstimatedCost,
		&i.CreatedAt,
	)
	return i, err
}

const logAITokenUsage = `-- name: LogAITokenUsage :one
INSERT INTO ai_token_logs (
    member_id, feature_used, prompt_tokens, completion_tokens, total_tokens
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, member_id, feature_used, prompt_tokens, completion_tokens, total_tokens, created_at
`

type LogAITokenUsageParams struct {
	MemberID         uuid.UUID `json:"member_id"`
	FeatureUsed      string    `json:"feature_used"`
	PromptTokens     int32     `json:"prompt_tokens"`
	CompletionTokens int32     `json:"completion_tokens"`
	TotalTokens      int32     `json:"total_tokens"`
}

func (q *Queries) LogAITokenUsage(ctx context.Context, arg LogAITokenUsageParams) (AiTokenLog, error) {
	row := q.db.QueryRowContext(ctx, logAITokenUsage,
		arg.MemberID,
		arg.FeatureUsed,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
	)
	var i AiTokenLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.FeatureUsed,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.CreatedAt,
	)
	return i, err
}

const updateAIPromptGlobal = `-- name: UpdateAIPromptGlobal :exec
INSERT INTO ai_prompts (prompt_type, prompt_text, is_active, admin_id, updated_at)
VALUES ($1, $2, $3, NULL, NOW())
ON CONFLICT (prompt_type) WHERE admin_id IS NULL
DO UPDATE SET prompt_text = EXCLUDED.prompt_text, is_active = EXCLUDED.is_active, updated_at = NOW()
`

type UpdateAIPromptGlobalParams struct {
	PromptType string `json:"prompt_type"`
	PromptText string `json:"prompt_text"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) UpdateAIPromptGlobal(ctx context.Context, arg UpdateAIPromptGlobalParams) error {
	_, err := q.db.ExecContext(ctx, updateAIPromptGlobal, arg.PromptType, arg.PromptText, arg.IsActive)
	return err
}

const updateAIPromptTenant = `-- name: UpdateAIPromptTenant :exec
INSERT INTO ai_prompts (prompt_type, prompt_text, is_active, admin_id, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (prompt_type, admin_id) WHERE admin_id IS NOT NULL
DO UPDATE SET prompt_text = EXCLUDED.prompt_text, is_active = EXCLUDED.is_active, updated_at = NOW()
`

type UpdateAIPromptTenantParams struct {
	PromptType string        `json:"prompt_type"`
	PromptText string        `json:"prompt_text"`
	IsActive   bool          `json:"is_active"`
	AdminID    uuid.NullUUID `json:"admin_id"`
}

func (q *Queries) UpdateAIPromptTenant(ctx context.Context, arg UpdateAIPromptTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateAIPromptTenant,
		arg.PromptType,
		arg.PromptText,
		arg.IsActive,
		arg.AdminID,
	)
	return err
}

const updateMemberAIProfile = `-- name: UpdateMemberAIProfile :one
UPDATE members
SET budget_level = $2, is_ai_allowed = $3, is_ai_food_log_allowed = $4, profile_picture_url = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, phone, password_hash, goal, join_date, current_weight, status, must_change_password, created_at, updated_at, height_cm, date_of_birth, religion, blood_group, hobbies, present_address, permanent_address, occupation, nid, emergency_phone, gender, budget_level, is_ai_allowed, profile_picture_url, diet_chart_json, is_ai_food_log_allowed, pending_diet_chart_json, created_by_admin_id
`

type UpdateMemberAIProfileParams struct {
	ID                 uuid.UUID      `json:"id"`
	BudgetLevel        sql.NullString `json:"budget_level"`
	IsAiAllowed        bool           `json:"is_ai_allowed"`
	IsAiFoodLogAllowed bool           `json:"is_ai_food_log_allowed"`
	ProfilePictureUrl  sql.NullString `json:"profile_picture_url"`
}

func (q *Queries) UpdateMemberAIProfile(ctx context.Context, arg UpdateMemberAIProfileParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMemberAIProfile,
		arg.ID,
		arg.BudgetLevel,
		arg.IsAiAllowed,
		arg.IsAiFoodLogAllowed,
		arg.ProfilePictureUrl,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.PasswordHash,
		&i.Goal,
		&i.JoinDate,
		&i.CurrentWeight,
		&i.Status,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeightCm,
		&i.DateOfBirth,
		&i.Religion,
		&i.BloodGroup,
		pq.Array(&i.Hobbies),
		&i.PresentAddress,
		&i.PermanentAddress,
		&i.Occupation,
		&i.Nid,
		&i.EmergencyPhone,
		&i.Gender,
		&i.BudgetLevel,
		&i.IsAiAllowed,
		&i.ProfilePictureUrl,
		&i.DietChartJson,
		&i.IsAiFoodLogAllowed,
		&i.PendingDietChartJson,
		&i.CreatedByAdminID,
	)
	return i, err
}

const updateSystemSetting = `-- name: UpdateSystemSetting :exec
INSERT INTO system_settings (setting_key, setting_value, admin_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (setting_key, admin_id) DO UPDATE SET setting_value = $2, updated_at = NOW()
`

type UpdateSystemSettingParams struct {
	SettingKey   string        `json:"setting_key"`
	SettingValue string        `json:"setting_value"`
	AdminID      uuid.NullUUID `json:"admin_id"`
}

func (q *Queries) UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemSetting, arg.SettingKey, arg.SettingValue, arg.AdminID)
	return err
}
