// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diet_logs.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDietLog = `-- name: CreateDietLog :one
INSERT INTO diet_logs (id, member_id, content, logged_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, content, logged_at
`

type CreateDietLogParams struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	Content  string    `json:"content"`
	LoggedAt time.Time `json:"logged_at"`
}

func (q *Queries) CreateDietLog(ctx context.Context, arg CreateDietLogParams) (DietLog, error) {
	row := q.db.QueryRowContext(ctx, createDietLog,
		arg.ID,
		arg.MemberID,
		arg.Content,
		arg.LoggedAt,
	)
	var i DietLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Content,
		&i.LoggedAt,
	)
	return i, err
}

const listDietLogsByMemberID = `-- name: ListDietLogsByMemberID :many
SELECT id, member_id, content, logged_at FROM diet_logs
WHERE member_id = $1
ORDER BY logged_at DESC
LIMIT  $3::int
OFFSET $2::int
`

type ListDietLogsByMemberIDParams struct {
	MemberID    uuid.UUID `json:"member_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

func (q *Queries) ListDietLogsByMemberID(ctx context.Context, arg ListDietLogsByMemberIDParams) ([]DietLog, error) {
	rows, err := q.db.QueryContext(ctx, listDietLogsByMemberID, arg.MemberID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DietLog
	for rows.Next() {
		var i DietLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Content,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
