// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*) FROM expenses
WHERE ($1::timestamptz IS NULL OR spent_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR spent_at <= $2::timestamptz)
`

type CountExpensesParams struct {
	FromTime sql.NullTime `json:"from_time"`
	ToTime   sql.NullTime `json:"to_time"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExpenses, arg.FromTime, arg.ToTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, amount, description, category, spent_at, recorded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, amount, description, category, spent_at, recorded_by, created_at, updated_at
`

type CreateExpenseParams struct {
	ID          uuid.UUID `json:"id"`
	Amount      float64   `json:"amount"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	SpentAt     time.Time `json:"spent_at"`
	RecordedBy  uuid.UUID `json:"recorded_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.Category,
		arg.SpentAt,
		arg.RecordedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.Category,
		&i.SpentAt,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyFinancialsByMonth = `-- name: GetDailyFinancialsByMonth :many
WITH daily_payments AS (
    SELECT
        (paid_at AT TIME ZONE $1::text)::date AS trans_date,
        COALESCE(SUM(amount), 0)::float8 AS total_earnings
    FROM payments
    WHERE paid_at >= $2::timestamptz AND paid_at < $3::timestamptz
    GROUP BY 1
),
daily_expenses AS (
    SELECT
        (spent_at AT TIME ZONE $1::text)::date AS trans_date,
        COALESCE(SUM(amount), 0)::float8 AS total_expenses
    FROM expenses
    WHERE spent_at >= $2::timestamptz AND spent_at < $3::timestamptz
    GROUP BY 1
),
all_dates AS (
    SELECT trans_date FROM daily_payments
    UNION
    SELECT trans_date FROM daily_expenses
)
SELECT
    all_dates.trans_date AS date,
    COALESCE(p.total_earnings, 0)::float8 AS earnings,
    COALESCE(e.total_expenses, 0)::float8 AS expenses,
    (COALESCE(p.total_earnings, 0) - COALESCE(e.total_expenses, 0))::float8 AS net
FROM all_dates
LEFT JOIN daily_payments p ON all_dates.trans_date = p.trans_date
LEFT JOIN daily_expenses e ON all_dates.trans_date = e.trans_date
ORDER BY all_dates.trans_date ASC
`

type GetDailyFinancialsByMonthParams struct {
	Timezone  string    `json:"timezone"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetDailyFinancialsByMonthRow struct {
	Date     time.Time `json:"date"`
	Earnings float64   `json:"earnings"`
	Expenses float64   `json:"expenses"`
	Net      float64   `json:"net"`
}

func (q *Queries) GetDailyFinancialsByMonth(ctx context.Context, arg GetDailyFinancialsByMonthParams) ([]GetDailyFinancialsByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyFinancialsByMonth, arg.Timezone, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyFinancialsByMonthRow
	for rows.Next() {
		var i GetDailyFinancialsByMonthRow
		if err := rows.Scan(
			&i.Date,
			&i.Earnings,
			&i.Expenses,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesSummary = `-- name: GetExpensesSummary :one
SELECT
    COALESCE(SUM(CASE WHEN spent_at >= $1::timestamptz AND spent_at < $2::timestamptz THEN amount ELSE 0 END), 0)::float8 AS today_total,
    COALESCE(SUM(CASE WHEN spent_at >= $3::timestamptz AND spent_at < $4::timestamptz THEN amount ELSE 0 END), 0)::float8 AS yesterday_total,
    COALESCE(SUM(CASE WHEN spent_at >= $5::timestamptz AND spent_at < $6::timestamptz THEN amount ELSE 0 END), 0)::float8 AS month_total
FROM expenses
`

type GetExpensesSummaryParams struct {
	TodayStart     time.Time `json:"today_start"`
	TodayEnd       time.Time `json:"today_end"`
	YesterdayStart time.Time `json:"yesterday_start"`
	YesterdayEnd   time.Time `json:"yesterday_end"`
	MonthStart     time.Time `json:"month_start"`
	MonthEnd       time.Time `json:"month_end"`
}

type GetExpensesSummaryRow struct {
	TodayTotal     float64 `json:"today_total"`
	YesterdayTotal float64 `json:"yesterday_total"`
	MonthTotal     float64 `json:"month_total"`
}

func (q *Queries) GetExpensesSummary(ctx context.Context, arg GetExpensesSummaryParams) (GetExpensesSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getExpensesSummary,
		arg.TodayStart,
		arg.TodayEnd,
		arg.YesterdayStart,
		arg.YesterdayEnd,
		arg.MonthStart,
		arg.MonthEnd,
	)
	var i GetExpensesSummaryRow
	err := row.Scan(&i.TodayTotal, &i.YesterdayTotal, &i.MonthTotal)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, amount, description, category, spent_at, recorded_by, created_at, updated_at FROM expenses
WHERE ($1::timestamptz IS NULL OR spent_at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR spent_at <= $2::timestamptz)
ORDER BY spent_at DESC
LIMIT $4::int
OFFSET $3::int
`

type ListExpensesParams struct {
	FromTime  sql.NullTime `json:"from_time"`
	ToTime    sql.NullTime `json:"to_time"`
	OffsetVal int32        `json:"offset_val"`
	LimitVal  int32        `json:"limit_val"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses,
		arg.FromTime,
		arg.ToTime,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Description,
			&i.Category,
			&i.SpentAt,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
