// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fcm_tokens.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteFCMToken = `-- name: DeleteFCMToken :exec
DELETE FROM fcm_tokens WHERE token = $1
`

func (q *Queries) DeleteFCMToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteFCMToken, token)
	return err
}

const deleteFCMTokensByMemberID = `-- name: DeleteFCMTokensByMemberID :exec
DELETE FROM fcm_tokens WHERE member_id = $1
`

func (q *Queries) DeleteFCMTokensByMemberID(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFCMTokensByMemberID, memberID)
	return err
}

const listFCMTokensByMemberID = `-- name: ListFCMTokensByMemberID :many
SELECT id, member_id, token, device_info, last_active_at, created_at FROM fcm_tokens
WHERE member_id = $1
ORDER BY last_active_at DESC
`

func (q *Queries) ListFCMTokensByMemberID(ctx context.Context, memberID uuid.UUID) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, listFCMTokensByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FcmToken
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Token,
			&i.DeviceInfo,
			&i.LastActiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFCMToken = `-- name: UpsertFCMToken :one
INSERT INTO fcm_tokens (id, member_id, token, device_info, last_active_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (token)
DO UPDATE SET
    member_id      = EXCLUDED.member_id,
    device_info    = EXCLUDED.device_info,
    last_active_at = NOW()
RETURNING id, member_id, token, device_info, last_active_at, created_at
`

type UpsertFCMTokenParams struct {
	ID         uuid.UUID      `json:"id"`
	MemberID   uuid.UUID      `json:"member_id"`
	Token      string         `json:"token"`
	DeviceInfo sql.NullString `json:"device_info"`
}

func (q *Queries) UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, upsertFCMToken,
		arg.ID,
		arg.MemberID,
		arg.Token,
		arg.DeviceInfo,
	)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Token,
		&i.DeviceInfo,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}
