// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financials.sql

package sqlcdb

import (
	"context"
	"time"
)

const getExpensesByCategory = `-- name: GetExpensesByCategory :many
SELECT
    e.category::text AS category,
    COALESCE(SUM(e.amount), 0)::float8 AS total_amount,
    COUNT(e.id)::int8 AS expense_count
FROM expenses e
WHERE e.spent_at >= $1::timestamptz AND e.spent_at < $2::timestamptz
GROUP BY e.category
ORDER BY total_amount DESC
`

type GetExpensesByCategoryParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetExpensesByCategoryRow struct {
	Category     string  `json:"category"`
	TotalAmount  float64 `json:"total_amount"`
	ExpenseCount int64   `json:"expense_count"`
}

// Group operational costs by category over a date range
func (q *Queries) GetExpensesByCategory(ctx context.Context, arg GetExpensesByCategoryParams) ([]GetExpensesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpensesByCategory, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpensesByCategoryRow
	for rows.Next() {
		var i GetExpensesByCategoryRow
		if err := rows.Scan(&i.Category, &i.TotalAmount, &i.ExpenseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByPaymentMethod = `-- name: GetRevenueByPaymentMethod :many
SELECT
    p.method::text AS payment_method,
    COALESCE(SUM(p.amount), 0)::float8 AS total_amount,
    COUNT(p.id)::int8 AS transaction_count
FROM payments p
WHERE p.paid_at >= $1::timestamptz AND p.paid_at < $2::timestamptz
GROUP BY p.method
ORDER BY total_amount DESC
`

type GetRevenueByPaymentMethodParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetRevenueByPaymentMethodRow struct {
	PaymentMethod    string  `json:"payment_method"`
	TotalAmount      float64 `json:"total_amount"`
	TransactionCount int64   `json:"transaction_count"`
}

// Group subscription payments by method over a date range
func (q *Queries) GetRevenueByPaymentMethod(ctx context.Context, arg GetRevenueByPaymentMethodParams) ([]GetRevenueByPaymentMethodRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueByPaymentMethod, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByPaymentMethodRow
	for rows.Next() {
		var i GetRevenueByPaymentMethodRow
		if err := rows.Scan(&i.PaymentMethod, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByPlanType = `-- name: GetRevenueByPlanType :many
SELECT
    pt.name::text AS plan_name,
    pt.default_price::float8 AS plan_price,
    COALESCE(SUM(p.amount), 0)::float8 AS total_amount,
    COUNT(p.id)::int8 AS transaction_count
FROM payments p
JOIN subscriptions s ON p.subscription_id = s.id
JOIN plan_templates pt ON s.plan_template_id = pt.id
WHERE p.paid_at >= $1::timestamptz AND p.paid_at < $2::timestamptz
GROUP BY pt.name, pt.default_price
ORDER BY total_amount DESC
`

type GetRevenueByPlanTypeParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetRevenueByPlanTypeRow struct {
	PlanName         string  `json:"plan_name"`
	PlanPrice        float64 `json:"plan_price"`
	TotalAmount      float64 `json:"total_amount"`
	TransactionCount int64   `json:"transaction_count"`
}

// Group subscription payments by plan name over a date range
func (q *Queries) GetRevenueByPlanType(ctx context.Context, arg GetRevenueByPlanTypeParams) ([]GetRevenueByPlanTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueByPlanType, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByPlanTypeRow
	for rows.Next() {
		var i GetRevenueByPlanTypeRow
		if err := rows.Scan(
			&i.PlanName,
			&i.PlanPrice,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
