// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at, read_at
`

type CreateMessageParams struct {
	ID              uuid.UUID      `json:"id"`
	SenderID        uuid.UUID      `json:"sender_id"`
	SenderRole      string         `json:"sender_role"`
	ReceiverID      uuid.NullUUID  `json:"receiver_id"`
	IsBroadcast     bool           `json:"is_broadcast"`
	BroadcastFilter sql.NullString `json:"broadcast_filter"`
	Content         string         `json:"content"`
	SentAt          time.Time      `json:"sent_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SenderID,
		arg.SenderRole,
		arg.ReceiverID,
		arg.IsBroadcast,
		arg.BroadcastFilter,
		arg.Content,
		arg.SentAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.SenderRole,
		&i.ReceiverID,
		&i.IsBroadcast,
		&i.BroadcastFilter,
		&i.Content,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}

const getLatestDirectMessageByMember = `-- name: GetLatestDirectMessageByMember :one
SELECT id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at, read_at FROM messages
WHERE is_broadcast = FALSE
  AND (
      (sender_role = 'member' AND sender_id   = $1)
   OR (sender_role = 'admin'  AND receiver_id = $1)
  )
ORDER BY sent_at DESC
LIMIT 1
`

// Used to build the conversation summary list.
func (q *Queries) GetLatestDirectMessageByMember(ctx context.Context, memberID uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLatestDirectMessageByMember, memberID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.SenderRole,
		&i.ReceiverID,
		&i.IsBroadcast,
		&i.BroadcastFilter,
		&i.Content,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}

const listBroadcasts = `-- name: ListBroadcasts :many
SELECT id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at, read_at FROM messages
WHERE is_broadcast = TRUE
ORDER BY sent_at DESC
LIMIT  $2::int
OFFSET $1::int
`

type ListBroadcastsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListBroadcasts(ctx context.Context, arg ListBroadcastsParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listBroadcasts, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderRole,
			&i.ReceiverID,
			&i.IsBroadcast,
			&i.BroadcastFilter,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMemberIDs = `-- name: ListConversationMemberIDs :many
SELECT DISTINCT
    CASE
        WHEN sender_role = 'member' THEN sender_id
        ELSE receiver_id
    END AS member_id
FROM messages
WHERE is_broadcast = FALSE
ORDER BY member_id
`

// Returns one row per member who has exchanged a direct message with admin.
func (q *Queries) ListConversationMemberIDs(ctx context.Context) ([]interface{}, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMemberIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var member_id interface{}
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectMessagesByMember = `-- name: ListDirectMessagesByMember :many
SELECT id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at, read_at FROM messages
WHERE is_broadcast = FALSE
  AND (
      (sender_role = 'member' AND sender_id   = $1)
   OR (sender_role = 'admin'  AND receiver_id = $1)
  )
ORDER BY sent_at ASC
`

// Returns the direct conversation between admin and a specific member.
func (q *Queries) ListDirectMessagesByMember(ctx context.Context, memberID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listDirectMessagesByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderRole,
			&i.ReceiverID,
			&i.IsBroadcast,
			&i.BroadcastFilter,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberMessages = `-- name: ListMemberMessages :many
SELECT id, sender_id, sender_role, receiver_id, is_broadcast, broadcast_filter, content, sent_at, read_at FROM messages
WHERE (
    (is_broadcast = FALSE AND (
        (sender_role = 'member' AND sender_id   = $1)
     OR (sender_role = 'admin'  AND receiver_id = $1)
    ))
    OR is_broadcast = TRUE
)
ORDER BY sent_at DESC
LIMIT  $3::int
OFFSET $2::int
`

type ListMemberMessagesParams struct {
	MemberID    uuid.UUID `json:"member_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

// All messages relevant to a member: direct (both directions) + all broadcasts.
func (q *Queries) ListMemberMessages(ctx context.Context, arg ListMemberMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMemberMessages, arg.MemberID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.SenderRole,
			&i.ReceiverID,
			&i.IsBroadcast,
			&i.BroadcastFilter,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdminMessagesAsRead = `-- name: MarkAdminMessagesAsRead :exec
UPDATE messages
SET read_at = NOW()
WHERE sender_role  = 'admin'
  AND receiver_id  = $1
  AND is_broadcast = FALSE
  AND read_at IS NULL
`

// Member opens their inbox: mark unread admin→member messages as read.
func (q *Queries) MarkAdminMessagesAsRead(ctx context.Context, memberID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, markAdminMessagesAsRead, memberID)
	return err
}

const markMemberMessagesAsRead = `-- name: MarkMemberMessagesAsRead :exec
UPDATE messages
SET read_at = NOW()
WHERE sender_role  = 'member'
  AND sender_id    = $1
  AND is_broadcast = FALSE
  AND read_at IS NULL
`

// Admin opens a conversation: mark unread member→admin messages as read.
func (q *Queries) MarkMemberMessagesAsRead(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markMemberMessagesAsRead, memberID)
	return err
}
