// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Phone        sql.NullString `json:"phone"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type DietLog struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	Content  string    `json:"content"`
	LoggedAt time.Time `json:"logged_at"`
}

type FcmToken struct {
	ID           uuid.UUID      `json:"id"`
	MemberID     uuid.UUID      `json:"member_id"`
	Token        string         `json:"token"`
	DeviceInfo   sql.NullString `json:"device_info"`
	LastActiveAt time.Time      `json:"last_active_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Member struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	Phone              string          `json:"phone"`
	PasswordHash       string          `json:"password_hash"`
	Goal               sql.NullString  `json:"goal"`
	JoinDate           time.Time       `json:"join_date"`
	CurrentWeight      sql.NullFloat64 `json:"current_weight"`
	Status             string          `json:"status"`
	MustChangePassword bool            `json:"must_change_password"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type Message struct {
	ID              uuid.UUID      `json:"id"`
	SenderID        uuid.UUID      `json:"sender_id"`
	SenderRole      string         `json:"sender_role"`
	ReceiverID      uuid.NullUUID  `json:"receiver_id"`
	IsBroadcast     bool           `json:"is_broadcast"`
	BroadcastFilter sql.NullString `json:"broadcast_filter"`
	Content         string         `json:"content"`
	SentAt          time.Time      `json:"sent_at"`
	ReadAt          sql.NullTime   `json:"read_at"`
}

type Notification struct {
	ID          uuid.UUID       `json:"id"`
	MemberID    uuid.UUID       `json:"member_id"`
	Type        string          `json:"type"`
	Payload     json.RawMessage `json:"payload"`
	ScheduledAt time.Time       `json:"scheduled_at"`
	SentAt      sql.NullTime    `json:"sent_at"`
	Status      string          `json:"status"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID `json:"id"`
	MemberID          uuid.UUID `json:"member_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	Amount            float64   `json:"amount"`
	Method            string    `json:"method"`
	PaidAt            time.Time `json:"paid_at"`
	RecordedByAdminID uuid.UUID `json:"recorded_by_admin_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type PlanTemplate struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	DurationDays int32     `json:"duration_days"`
	DefaultPrice float64   `json:"default_price"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Setting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Subscription struct {
	ID             uuid.UUID      `json:"id"`
	MemberID       uuid.UUID      `json:"member_id"`
	PlanTemplateID uuid.UUID      `json:"plan_template_id"`
	StartDate      time.Time      `json:"start_date"`
	EndDate        time.Time      `json:"end_date"`
	FinalPrice     float64        `json:"final_price"`
	Note           sql.NullString `json:"note"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
}

type SystemLog struct {
	ID        uuid.UUID             `json:"id"`
	Level     string                `json:"level"`
	Message   string                `json:"message"`
	RequestID uuid.NullUUID         `json:"request_id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Route     sql.NullString        `json:"route"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

type WeightLog struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	WeightKg float64   `json:"weight_kg"`
	LoggedAt time.Time `json:"logged_at"`
}

type WorkoutLog struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	Content  string    `json:"content"`
	LoggedAt time.Time `json:"logged_at"`
}
