// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, member_id, type, payload, scheduled_at, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, type, payload, scheduled_at, sent_at, status, created_at
`

type CreateNotificationParams struct {
	ID          uuid.UUID       `json:"id"`
	MemberID    uuid.UUID       `json:"member_id"`
	Type        string          `json:"type"`
	Payload     json.RawMessage `json:"payload"`
	ScheduledAt time.Time       `json:"scheduled_at"`
	Status      string          `json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.MemberID,
		arg.Type,
		arg.Payload,
		arg.ScheduledAt,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Type,
		&i.Payload,
		&i.ScheduledAt,
		&i.SentAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, member_id, type, payload, scheduled_at, sent_at, status, created_at FROM notifications
WHERE status      = 'pending'
  AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC
LIMIT 200
`

// Pulled every minute by the scheduler to dispatch overdue notifications.
func (q *Queries) ListPendingNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Type,
			&i.Payload,
			&i.ScheduledAt,
			&i.SentAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleNotification = `-- name: RescheduleNotification :exec
UPDATE notifications
SET scheduled_at = $1
WHERE id         = $2
`

type RescheduleNotificationParams struct {
	ScheduledAt time.Time `json:"scheduled_at"`
	ID          uuid.UUID `json:"id"`
}

// Move a notification past the quiet window without changing its status.
func (q *Queries) RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleNotification, arg.ScheduledAt, arg.ID)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status  = $1,
    sent_at = CASE WHEN $1::text = 'sent' THEN NOW() ELSE sent_at END
WHERE id    = $2
`

type UpdateNotificationStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationStatus, arg.Status, arg.ID)
	return err
}
