// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, member_id, subscription_id, amount, method, paid_at, recorded_by_admin_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, member_id, subscription_id, amount, method, paid_at, recorded_by_admin_id, created_at
`

type CreatePaymentParams struct {
	ID                uuid.UUID `json:"id"`
	MemberID          uuid.UUID `json:"member_id"`
	SubscriptionID    uuid.UUID `json:"subscription_id"`
	Amount            float64   `json:"amount"`
	Method            string    `json:"method"`
	PaidAt            time.Time `json:"paid_at"`
	RecordedByAdminID uuid.UUID `json:"recorded_by_admin_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.ID,
		arg.MemberID,
		arg.SubscriptionID,
		arg.Amount,
		arg.Method,
		arg.PaidAt,
		arg.RecordedByAdminID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Method,
		&i.PaidAt,
		&i.RecordedByAdminID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentSummaryByMonth = `-- name: GetPaymentSummaryByMonth :one
SELECT
    COALESCE(SUM(amount), 0)::float8 AS total_amount,
    COUNT(*)                          AS payment_count
FROM payments
WHERE date_trunc('month', paid_at) = date_trunc('month', $1::timestamptz)
`

type GetPaymentSummaryByMonthRow struct {
	TotalAmount  float64 `json:"total_amount"`
	PaymentCount int64   `json:"payment_count"`
}

func (q *Queries) GetPaymentSummaryByMonth(ctx context.Context, month time.Time) (GetPaymentSummaryByMonthRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentSummaryByMonth, month)
	var i GetPaymentSummaryByMonthRow
	err := row.Scan(&i.TotalAmount, &i.PaymentCount)
	return i, err
}

const listPaymentsByMember = `-- name: ListPaymentsByMember :many
SELECT id, member_id, subscription_id, amount, method, paid_at, recorded_by_admin_id, created_at FROM payments
WHERE member_id = $1
  AND ($2::timestamptz IS NULL OR paid_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR paid_at <= $3::timestamptz)
ORDER BY paid_at DESC
`

type ListPaymentsByMemberParams struct {
	MemberID uuid.UUID    `json:"member_id"`
	FromTime sql.NullTime `json:"from_time"`
	ToTime   sql.NullTime `json:"to_time"`
}

// Supports optional date range; pass NULL for from_time / to_time to skip filter.
func (q *Queries) ListPaymentsByMember(ctx context.Context, arg ListPaymentsByMemberParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByMember, arg.MemberID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.SubscriptionID,
			&i.Amount,
			&i.Method,
			&i.PaidAt,
			&i.RecordedByAdminID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
