// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_templates.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createPlanTemplate = `-- name: CreatePlanTemplate :one
INSERT INTO plan_templates (id, name, duration_days, default_price)
VALUES ($1, $2, $3, $4)
RETURNING id, name, duration_days, default_price, created_at, updated_at
`

type CreatePlanTemplateParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	DurationDays int32     `json:"duration_days"`
	DefaultPrice float64   `json:"default_price"`
}

func (q *Queries) CreatePlanTemplate(ctx context.Context, arg CreatePlanTemplateParams) (PlanTemplate, error) {
	row := q.db.QueryRowContext(ctx, createPlanTemplate,
		arg.ID,
		arg.Name,
		arg.DurationDays,
		arg.DefaultPrice,
	)
	var i PlanTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.DefaultPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlanTemplate = `-- name: DeletePlanTemplate :exec
DELETE FROM plan_templates WHERE id = $1
`

func (q *Queries) DeletePlanTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlanTemplate, id)
	return err
}

const getPlanTemplateByID = `-- name: GetPlanTemplateByID :one
SELECT id, name, duration_days, default_price, created_at, updated_at FROM plan_templates WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanTemplateByID(ctx context.Context, id uuid.UUID) (PlanTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPlanTemplateByID, id)
	var i PlanTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.DefaultPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlanTemplates = `-- name: ListPlanTemplates :many
SELECT id, name, duration_days, default_price, created_at, updated_at FROM plan_templates ORDER BY created_at DESC
`

func (q *Queries) ListPlanTemplates(ctx context.Context) ([]PlanTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listPlanTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanTemplate
	for rows.Next() {
		var i PlanTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationDays,
			&i.DefaultPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanTemplate = `-- name: UpdatePlanTemplate :one
UPDATE plan_templates
SET name          = $1,
    duration_days = $2,
    default_price = $3,
    updated_at    = NOW()
WHERE id = $4
RETURNING id, name, duration_days, default_price, created_at, updated_at
`

type UpdatePlanTemplateParams struct {
	Name         string    `json:"name"`
	DurationDays int32     `json:"duration_days"`
	DefaultPrice float64   `json:"default_price"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePlanTemplate(ctx context.Context, arg UpdatePlanTemplateParams) (PlanTemplate, error) {
	row := q.db.QueryRowContext(ctx, updatePlanTemplate,
		arg.Name,
		arg.DurationDays,
		arg.DefaultPrice,
		arg.ID,
	)
	var i PlanTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationDays,
		&i.DefaultPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
