// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile_picture_updates.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countProfilePictureUpdates = `-- name: CountProfilePictureUpdates :one
SELECT COUNT(*)
FROM profile_picture_updates
WHERE member_id = $1 AND updated_by_role = $2
`

type CountProfilePictureUpdatesParams struct {
	MemberID      uuid.UUID `json:"member_id"`
	UpdatedByRole string    `json:"updated_by_role"`
}

func (q *Queries) CountProfilePictureUpdates(ctx context.Context, arg CountProfilePictureUpdatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProfilePictureUpdates, arg.MemberID, arg.UpdatedByRole)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordProfilePictureUpdate = `-- name: RecordProfilePictureUpdate :one
INSERT INTO profile_picture_updates (member_id, updated_by_role, updated_by_id)
VALUES ($1, $2, $3)
RETURNING id, member_id, updated_by_role, updated_by_id, created_at
`

type RecordProfilePictureUpdateParams struct {
	MemberID      uuid.UUID `json:"member_id"`
	UpdatedByRole string    `json:"updated_by_role"`
	UpdatedByID   uuid.UUID `json:"updated_by_id"`
}

func (q *Queries) RecordProfilePictureUpdate(ctx context.Context, arg RecordProfilePictureUpdateParams) (ProfilePictureUpdate, error) {
	row := q.db.QueryRowContext(ctx, recordProfilePictureUpdate, arg.MemberID, arg.UpdatedByRole, arg.UpdatedByID)
	var i ProfilePictureUpdate
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.UpdatedByRole,
		&i.UpdatedByID,
		&i.CreatedAt,
	)
	return i, err
}
