// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountMembers(ctx context.Context, arg CountMembersParams) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateDietLog(ctx context.Context, arg CreateDietLogParams) (DietLog, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlanTemplate(ctx context.Context, arg CreatePlanTemplateParams) (PlanTemplate, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateWeightLog(ctx context.Context, arg CreateWeightLogParams) (WeightLog, error)
	CreateWorkoutLog(ctx context.Context, arg CreateWorkoutLogParams) (WorkoutLog, error)
	DeleteFCMToken(ctx context.Context, token string) error
	DeleteFCMTokensByMemberID(ctx context.Context, memberID uuid.UUID) error
	DeletePlanTemplate(ctx context.Context, id uuid.UUID) error
	GetActiveSubscriptionByMemberID(ctx context.Context, memberID uuid.UUID) (Subscription, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAdminByPhone(ctx context.Context, phone sql.NullString) (Admin, error)
	GetAllSettings(ctx context.Context) ([]Setting, error)
	// Used to build the conversation summary list.
	GetLatestDirectMessageByMember(ctx context.Context, memberID uuid.UUID) (Message, error)
	GetLatestWeightLogByMemberID(ctx context.Context, memberID uuid.UUID) (WeightLog, error)
	GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error)
	GetMemberByPhone(ctx context.Context, phone string) (Member, error)
	GetPaymentSummaryByMonth(ctx context.Context, month time.Time) (GetPaymentSummaryByMonthRow, error)
	GetPlanTemplateByID(ctx context.Context, id uuid.UUID) (PlanTemplate, error)
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	ListAllPayments(ctx context.Context, arg ListAllPaymentsParams) ([]Payment, error)
	ListBroadcasts(ctx context.Context, arg ListBroadcastsParams) ([]Message, error)
	// Returns one row per member who has exchanged a direct message with admin.
	ListConversationMemberIDs(ctx context.Context) ([]interface{}, error)
	ListDietLogsByMemberID(ctx context.Context, arg ListDietLogsByMemberIDParams) ([]DietLog, error)
	// Returns the direct conversation between admin and a specific member.
	ListDirectMessagesByMember(ctx context.Context, memberID uuid.UUID) ([]Message, error)
	// Used by the renewal reminder scheduler. Returns active subs ending within @days days.
	ListExpiringSubscriptions(ctx context.Context, days int32) ([]ListExpiringSubscriptionsRow, error)
	ListFCMTokensByMemberID(ctx context.Context, memberID uuid.UUID) ([]FcmToken, error)
	// All messages relevant to a member: direct (both directions) + all broadcasts.
	ListMemberMessages(ctx context.Context, arg ListMemberMessagesParams) ([]Message, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error)
	// Active members who have not logged weight in the last @days days.
	ListMembersNeedingWeightReminder(ctx context.Context, days int32) ([]Member, error)
	// Returns active members whose active subscription ends within @days days.
	ListMembersWithExpiringSoon(ctx context.Context, days int32) ([]Member, error)
	// Supports optional date range; pass NULL for from_time / to_time to skip filter.
	ListPaymentsByMember(ctx context.Context, arg ListPaymentsByMemberParams) ([]Payment, error)
	// Pulled every minute by the scheduler to dispatch overdue notifications.
	ListPendingNotifications(ctx context.Context) ([]Notification, error)
	ListPlanTemplates(ctx context.Context) ([]PlanTemplate, error)
	ListSubscriptionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]Subscription, error)
	// Optional date range: pass NULL for from_time / to_time to skip that bound.
	ListWeightLogsByMember(ctx context.Context, arg ListWeightLogsByMemberParams) ([]WeightLog, error)
	ListWorkoutLogsByMemberID(ctx context.Context, arg ListWorkoutLogsByMemberIDParams) ([]WorkoutLog, error)
	// Member opens their inbox: mark unread admin→member messages as read.
	MarkAdminMessagesAsRead(ctx context.Context, memberID uuid.NullUUID) error
	// Admin opens a conversation: mark unread member→admin messages as read.
	MarkMemberMessagesAsRead(ctx context.Context, memberID uuid.UUID) error
	// Marks all current active subscriptions for a member as 'replaced' before assigning a new one.
	ReplaceActiveSubscriptions(ctx context.Context, memberID uuid.UUID) error
	// Move a notification past the quiet window without changing its status.
	RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) error
	// In-place patch of the current active subscription (price, end date, note).
	UpdateActiveSubscription(ctx context.Context, arg UpdateActiveSubscriptionParams) (Subscription, error)
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateMemberPassword(ctx context.Context, arg UpdateMemberPasswordParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	UpdatePlanTemplate(ctx context.Context, arg UpdatePlanTemplateParams) (PlanTemplate, error)
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error
	UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) (FcmToken, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
