// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getAllSettings = `-- name: GetAllSettings :many
WITH admin_settings AS (
    SELECT key, value, updated_at, admin_id,
           ROW_NUMBER() OVER (PARTITION BY key ORDER BY admin_id DESC NULLS LAST) as rn
    FROM settings
    WHERE admin_id = $1 OR admin_id IS NULL
)
SELECT key, value, updated_at, admin_id
FROM admin_settings
WHERE rn = 1
ORDER BY key
`

type GetAllSettingsRow struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	UpdatedAt time.Time       `json:"updated_at"`
	AdminID   uuid.NullUUID   `json:"admin_id"`
}

func (q *Queries) GetAllSettings(ctx context.Context, adminID uuid.NullUUID) ([]GetAllSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSettings, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSettingsRow
	for rows.Next() {
		var i GetAllSettingsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT key, value, updated_at, admin_id FROM settings
WHERE key = $1 AND (admin_id = $2 OR admin_id IS NULL)
ORDER BY admin_id DESC NULLS LAST
LIMIT 1
`

type GetSettingByKeyParams struct {
	Key     string        `json:"key"`
	AdminID uuid.NullUUID `json:"admin_id"`
}

func (q *Queries) GetSettingByKey(ctx context.Context, arg GetSettingByKeyParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByKey, arg.Key, arg.AdminID)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.AdminID,
	)
	return i, err
}

const upsertSettingGlobal = `-- name: UpsertSettingGlobal :one
INSERT INTO settings (key, value, admin_id, updated_at)
VALUES ($1, $2, NULL, NOW())
ON CONFLICT (key) WHERE admin_id IS NULL DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
RETURNING key, value, updated_at, admin_id
`

type UpsertSettingGlobalParams struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) UpsertSettingGlobal(ctx context.Context, arg UpsertSettingGlobalParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertSettingGlobal, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.AdminID,
	)
	return i, err
}

const upsertSettingTenant = `-- name: UpsertSettingTenant :one
INSERT INTO settings (key, value, admin_id, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (key, admin_id) WHERE admin_id IS NOT NULL DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
RETURNING key, value, updated_at, admin_id
`

type UpsertSettingTenantParams struct {
	Key     string          `json:"key"`
	Value   json.RawMessage `json:"value"`
	AdminID uuid.NullUUID   `json:"admin_id"`
}

func (q *Queries) UpsertSettingTenant(ctx context.Context, arg UpsertSettingTenantParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertSettingTenant, arg.Key, arg.Value, arg.AdminID)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.AdminID,
	)
	return i, err
}
