// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (id, member_id, plan_template_id, start_date, end_date, final_price, note, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, member_id, plan_template_id, start_date, end_date, final_price, note, status, created_at
`

type CreateSubscriptionParams struct {
	ID             uuid.UUID      `json:"id"`
	MemberID       uuid.UUID      `json:"member_id"`
	PlanTemplateID uuid.UUID      `json:"plan_template_id"`
	StartDate      time.Time      `json:"start_date"`
	EndDate        time.Time      `json:"end_date"`
	FinalPrice     float64        `json:"final_price"`
	Note           sql.NullString `json:"note"`
	Status         string         `json:"status"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ID,
		arg.MemberID,
		arg.PlanTemplateID,
		arg.StartDate,
		arg.EndDate,
		arg.FinalPrice,
		arg.Note,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.PlanTemplateID,
		&i.StartDate,
		&i.EndDate,
		&i.FinalPrice,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscriptionByMemberID = `-- name: GetActiveSubscriptionByMemberID :one
SELECT id, member_id, plan_template_id, start_date, end_date, final_price, note, status, created_at FROM subscriptions
WHERE member_id = $1
  AND status    = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByMemberID(ctx context.Context, memberID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionByMemberID, memberID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.PlanTemplateID,
		&i.StartDate,
		&i.EndDate,
		&i.FinalPrice,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiringSubscriptions = `-- name: ListExpiringSubscriptions :many
SELECT s.id, s.member_id, s.plan_template_id, s.start_date, s.end_date, s.final_price, s.note, s.status, s.created_at, m.name AS member_name
FROM subscriptions s
JOIN members m ON m.id = s.member_id
WHERE s.status   = 'active'
  AND s.end_date >= CURRENT_DATE
  AND s.end_date <= CURRENT_DATE + ($1::int * INTERVAL '1 day')
ORDER BY s.end_date ASC
`

type ListExpiringSubscriptionsRow struct {
	ID             uuid.UUID      `json:"id"`
	MemberID       uuid.UUID      `json:"member_id"`
	PlanTemplateID uuid.UUID      `json:"plan_template_id"`
	StartDate      time.Time      `json:"start_date"`
	EndDate        time.Time      `json:"end_date"`
	FinalPrice     float64        `json:"final_price"`
	Note           sql.NullString `json:"note"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	MemberName     string         `json:"member_name"`
}

// Used by the renewal reminder scheduler. Returns active subs ending within @days days.
func (q *Queries) ListExpiringSubscriptions(ctx context.Context, days int32) ([]ListExpiringSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringSubscriptions, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringSubscriptionsRow
	for rows.Next() {
		var i ListExpiringSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.PlanTemplateID,
			&i.StartDate,
			&i.EndDate,
			&i.FinalPrice,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByMemberID = `-- name: ListSubscriptionsByMemberID :many
SELECT id, member_id, plan_template_id, start_date, end_date, final_price, note, status, created_at FROM subscriptions
WHERE member_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.PlanTemplateID,
			&i.StartDate,
			&i.EndDate,
			&i.FinalPrice,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceActiveSubscriptions = `-- name: ReplaceActiveSubscriptions :exec
UPDATE subscriptions
SET status = 'replaced'
WHERE member_id = $1
  AND status    = 'active'
`

// Marks all current active subscriptions for a member as 'replaced' before assigning a new one.
func (q *Queries) ReplaceActiveSubscriptions(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, replaceActiveSubscriptions, memberID)
	return err
}

const updateActiveSubscription = `-- name: UpdateActiveSubscription :one
UPDATE subscriptions
SET final_price = $1,
    start_date  = $2,
    end_date    = $3,
    note        = $4
WHERE member_id = $5
  AND status    = 'active'
RETURNING id, member_id, plan_template_id, start_date, end_date, final_price, note, status, created_at
`

type UpdateActiveSubscriptionParams struct {
	FinalPrice float64        `json:"final_price"`
	StartDate  time.Time      `json:"start_date"`
	EndDate    time.Time      `json:"end_date"`
	Note       sql.NullString `json:"note"`
	MemberID   uuid.UUID      `json:"member_id"`
}

// In-place patch of the current active subscription (price, start date, end date, note).
func (q *Queries) UpdateActiveSubscription(ctx context.Context, arg UpdateActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, updateActiveSubscription,
		arg.FinalPrice,
		arg.StartDate,
		arg.EndDate,
		arg.Note,
		arg.MemberID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.PlanTemplateID,
		&i.StartDate,
		&i.EndDate,
		&i.FinalPrice,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET status = $1
WHERE id   = $2
`

type UpdateSubscriptionStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.Status, arg.ID)
	return err
}
