// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weight_logs.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createWeightLog = `-- name: CreateWeightLog :one
INSERT INTO weight_logs (id, member_id, weight_kg, logged_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, weight_kg, logged_at
`

type CreateWeightLogParams struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	WeightKg float64   `json:"weight_kg"`
	LoggedAt time.Time `json:"logged_at"`
}

func (q *Queries) CreateWeightLog(ctx context.Context, arg CreateWeightLogParams) (WeightLog, error) {
	row := q.db.QueryRowContext(ctx, createWeightLog,
		arg.ID,
		arg.MemberID,
		arg.WeightKg,
		arg.LoggedAt,
	)
	var i WeightLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WeightKg,
		&i.LoggedAt,
	)
	return i, err
}

const getLatestWeightLogByMemberID = `-- name: GetLatestWeightLogByMemberID :one
SELECT id, member_id, weight_kg, logged_at FROM weight_logs
WHERE member_id = $1
ORDER BY logged_at DESC
LIMIT 1
`

func (q *Queries) GetLatestWeightLogByMemberID(ctx context.Context, memberID uuid.UUID) (WeightLog, error) {
	row := q.db.QueryRowContext(ctx, getLatestWeightLogByMemberID, memberID)
	var i WeightLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.WeightKg,
		&i.LoggedAt,
	)
	return i, err
}

const listMembersNeedingWeightReminder = `-- name: ListMembersNeedingWeightReminder :many
SELECT m.id, m.name, m.phone, m.password_hash, m.goal, m.join_date, m.current_weight, m.status, m.must_change_password, m.created_at, m.updated_at, m.height_cm, m.date_of_birth, m.religion, m.blood_group, m.hobbies, m.present_address, m.permanent_address, m.occupation, m.nid, m.emergency_phone
FROM members m
WHERE m.status = 'active'
  AND NOT EXISTS (
      SELECT 1
      FROM weight_logs wl
      WHERE wl.member_id = m.id
        AND wl.logged_at >= NOW() - ($1::int * INTERVAL '1 day')
  )
`

// Active members who have not logged weight in the last @days days.
func (q *Queries) ListMembersNeedingWeightReminder(ctx context.Context, days int32) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersNeedingWeightReminder, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.PasswordHash,
			&i.Goal,
			&i.JoinDate,
			&i.CurrentWeight,
			&i.Status,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeightCm,
			&i.DateOfBirth,
			&i.Religion,
			&i.BloodGroup,
			pq.Array(&i.Hobbies),
			&i.PresentAddress,
			&i.PermanentAddress,
			&i.Occupation,
			&i.Nid,
			&i.EmergencyPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightLogsByMember = `-- name: ListWeightLogsByMember :many
SELECT id, member_id, weight_kg, logged_at FROM weight_logs
WHERE member_id = $1
  AND ($2::timestamptz IS NULL OR logged_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR logged_at <  $3::timestamptz)
ORDER BY logged_at DESC
`

type ListWeightLogsByMemberParams struct {
	MemberID uuid.UUID    `json:"member_id"`
	FromTime sql.NullTime `json:"from_time"`
	ToTime   sql.NullTime `json:"to_time"`
}

// Optional date range: pass NULL for from_time / to_time to skip that bound.
func (q *Queries) ListWeightLogsByMember(ctx context.Context, arg ListWeightLogsByMemberParams) ([]WeightLog, error) {
	rows, err := q.db.QueryContext(ctx, listWeightLogsByMember, arg.MemberID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeightLog
	for rows.Next() {
		var i WeightLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.WeightKg,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
