// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workout_logs.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkoutLog = `-- name: CreateWorkoutLog :one
INSERT INTO workout_logs (id, member_id, content, logged_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, content, logged_at
`

type CreateWorkoutLogParams struct {
	ID       uuid.UUID `json:"id"`
	MemberID uuid.UUID `json:"member_id"`
	Content  string    `json:"content"`
	LoggedAt time.Time `json:"logged_at"`
}

func (q *Queries) CreateWorkoutLog(ctx context.Context, arg CreateWorkoutLogParams) (WorkoutLog, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutLog,
		arg.ID,
		arg.MemberID,
		arg.Content,
		arg.LoggedAt,
	)
	var i WorkoutLog
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Content,
		&i.LoggedAt,
	)
	return i, err
}

const listWorkoutLogsByMemberID = `-- name: ListWorkoutLogsByMemberID :many
SELECT id, member_id, content, logged_at FROM workout_logs
WHERE member_id = $1
ORDER BY logged_at DESC
LIMIT  $3::int
OFFSET $2::int
`

type ListWorkoutLogsByMemberIDParams struct {
	MemberID    uuid.UUID `json:"member_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

func (q *Queries) ListWorkoutLogsByMemberID(ctx context.Context, arg ListWorkoutLogsByMemberIDParams) ([]WorkoutLog, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutLogsByMemberID, arg.MemberID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutLog
	for rows.Next() {
		var i WorkoutLog
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Content,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
